version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: data-redis
    restart: always
    volumes:
      - ./runtime/redis:/data:rw
    ports:
      - "6389:6379"
  db:
    privileged: true
    container_name: data-db
    image: mysql
    restart: always
    # ports:
    # - "3307:3306"
    volumes:
      - ./runtime/mysql:/var/lib/mysql
      # - ./config/mysql-latest/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    command:
      --default-authentication-plugin=mysql_native_password
      # --character-set-server=utf8mb4
      # --collation-server=utf8mb4_general_ci
  data-server:
    build: .
    container_name: data-server
    restart: always
    command: pm2-runtime start pm2-spv.json
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    volumes:
      - "./src/config/chains.json:/home/makerTransationData/dist/src/config/chains.json"
      - "./src/config/testnet.json:/home/makerTransationData/dist/src/config/testnet.json"
      - "./runtime:/home/makerTransationData/runtime"
      - "./src/config:/home/makerTransationData/dist/src/config"
      - "./pm2-spv.json:/home/makerTransationData/pm2-spv.json"
