version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: data-redis
    restart: always
    volumes:
      - ./runtime/redis:/data:rw
    ports:
      - "6389:6379"
  data-server:
    build: .
    container_name: data-server
    restart: always
    command: pm2-runtime start pm2.json
    ports:
      - '8001:8001'
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - './src/config/chains.json:/home/makerTransationData/dist/src/config/chains.json'
      - './src/config/testnet.json:/home/makerTransationData/dist/src/config/testnet.json'
      - './runtime:/home/makerTransationData/runtime'
      - './src/config:/home/makerTransationData/dist/src/config'
      - './pm2.json:/home/makerTransationData/pm2.json'
